### PR TITLE
Test run branch um7b

### PR DESCRIPTION
**Pull request by JhanSrbinovsky**
total balls up of first draft - just try new PR

### CODE REVIEW

**Comment by JhanSrbinovsky** [comment]
Thanks @anton-seaice, seems like we are back on track

**Comment by anton-seaice** [comment]
Hi @harshula - this still doesn't deploy

I think the issue might be that the access-esm1p6 spack package depends on 

`mom5@access-esm1.6`

https://github.com/ACCESS-NRI/spack-packages/blob/512b0e0940c798c712f6535624c537d5c55ccb56/packages/access-esm1p6/package.py#L33

?

**Comment by anton-seaice** [comment]
Hi @JhanSrbinovsky - sorry i messed around a bunch. I made a little progress in fixing the formatting of the spack.yaml, but it's still stuck

**Comment by anton-seaice** [comment]
Hi @JhanSrbinovsky - I changed a few lines to get the mom5 from esm1p5 to work, hopefully it still does what you want :)

**Comment by blimlim** [comment]
Thanks @anton-seaice for getting this working! Good idea adding the `access-em1p5` spec, me and Harshula were quite stuck on getting it working.

@JhanSrbinovsky, one thing that's missing from this branch is the hashes in the projections (as noticed by @harshula). See the following diff compared to the `update_cable3` branch.
```diff
         projections:
+          all: '{name}/{version}'
           access-esm1p6: '{name}/2024.10.0'
-          cice4: '{name}/2024.05.21-{hash:7}'
-          um7: '{name}/18-esm15-cable3-{hash:7}'
-          mom5: '{name}/dev_2024.08.14-{hash:7}'
+          cice4: '{name}/2024.05.21'
+          um7: '{name}/18-esm15-cable3'
+          mom5: '{name}/access-esm1.5_2024.08.23-{hash:7}'
```
Including the `-{hash:7}` at the end of these lines is important – as without them, the wrong package can be picked up.

**Comment by blimlim** [comment]
Hi @JhanSrbinovsky, @harshula has made required changes to the spack-packages that let us use MOM5 without generic tracers, and has a working deployment in PR #10 using the branch [update_cable3](https://github.com/ACCESS-NRI/ACCESS-ESM1.6/tree/update_cable3). 

To coordinate development and troubleshooting, would you be happy to move over to that branch and pull request, and close this current one when ready?

**Comment by JhanSrbinovsky** [comment]
> To coordinate development and troubleshooting, would you be happy to move over to that branch and pull request, and close this current one when ready?


OK - I'll move over now. If the same error Im getting persists I'll let you know over there

**Pull request closed without merging**
